### ISSUE TITLE
Expand the Kitten Photo Selection!

### ISSUE THREAD

**Issue by ghost** [rgrove/emergencykitten#7]
[Feel free to](http://thecatapi.com/).

**Comment by cyphar** [comment]
Since flickr has an [API](https://www.flickr.com/services/api/), which even allows you to [figure out what the license is](https://www.flickr.com/services/api/flickr.photos.licenses.getInfo.html) and whether it is compatible with what we're trying to do. There's probably even more sources of cute kittens.

**Comment by rgrove** [comment]
Emergency Kitten now fetches kittens from the Flickr API! Thanks for the suggestion. 😸
